language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install sass
  - npm install --quiet -g gulp bower
  - npm install
  - bower install

script: gulp

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "crimeisdown.com"
  skip_cleanup: true
  local-dir: "dist"
  #upload-dir: "$AWS_UPLOAD_DIR"
